formatVersion: 9
id: 9866fd2f-1330-4a08-b728-bf633ff36af1
title: Комментарии с названиями в YAML
description: |-
  Раздел бэклога: Данные и хранилища.

  Ссылки в файлах — голые Guid, человеку их трудно читать. При записи добавлять рядом комментарий с названием (`- aaaa… # Готово`); при чтении он игнорируется.
typeId: 52c69d59-658f-467b-8e64-0eb42c3dd961
statusId: 943a8e7d-9573-4e9f-a4e4-7f67d8473c7a
createdAt: 2026-10-01T15:51:12.8590050+00:00
updatedAt: 2026-10-01T15:51:12.8590050+00:00
series:
- seriesId: d7ef1523-7d8d-46f8-b3c1-996e24fbd2c1
  number: 3
