formatVersion: 9
id: b72d6faa-bb18-4271-be1c-c0ae8e7793bf
title: 'Консоль: флаг --all в list — всё без ограничения по количеству'
description: 'Во всех командах list добавить --all: вывести все элементы (например, все задачи), а не страницу (по умолчанию 50, максимум 200). Совместимость: --all вместе с --offset/--limit — ошибка; в --json формат тот же, но одной страницей со всеми элементами.'
typeId: 52c69d59-658f-467b-8e64-0eb42c3dd961
statusId: 30300951-beb2-495f-a290-2b36ae0f4920
createdAt: 2026-10-01T16:52:08.9803820+00:00
updatedAt: 2026-10-01T16:55:54.7734760+00:00
series:
- seriesId: d7ef1523-7d8d-46f8-b3c1-996e24fbd2c1
  number: 62
