formatVersion: 9
id: 1fdfe97a-7567-4652-ba3a-3e5c46311b2e
title: Связи между задачами из разных проектов
description: Связи сейчас только внутри проекта (хранятся в файле задачи, у проекта своя папка и свои типы связей). Для межпроектных нужно решить, где хранить связь и типы, как показывать на обеих сторонах и как учитывать права на сервере (участник одного проекта не видит другой). Зависит от TSK-63.
typeId: d4d2c639-a723-4157-92a4-e704ef534e1c
statusId: 943a8e7d-9573-4e9f-a4e4-7f67d8473c7a
createdAt: 2026-10-01T22:52:21.6123830+00:00
updatedAt: 2026-10-01T22:52:21.6123830+00:00
series:
- seriesId: d7ef1523-7d8d-46f8-b3c1-996e24fbd2c1
  number: 65
